version: '3.8'

services:
  cups:
    container_name: cups
    image: mm404/cups-avahi-airprint
    restart: always
    network_mode: "host"
    environment:
      CUPSADMIN: cups
      CUPSPASSWORD: cups
    volumes:
      - "./services:/services"
      - "./config:/config"
